export enum MessageType {
  HOST_CONNECT = "HOST_CONNECT",
  HOST_DISCONNECT = "HOST_DISCONNECT",
  CONNECT = "CONNECT",
  DISCONNECT = "DISCONNECT",
  START = "START",
  STOP = "STOP",
  CHAT = "CHAT",
  POLL = "POLL",
  POLL_VOTE = "POLL_VOTE",
}